// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR6c3Ad0brmryK_fpekSrmPHUK4ByeByM',
    appId: '1:759452227025:web:ee229d11c4073842febcf0',
    messagingSenderId: '759452227025',
    projectId: 'likealocal-c33e9',
    authDomain: 'likealocal-c33e9.firebaseapp.com',
    storageBucket: 'likealocal-c33e9.firebasestorage.app',
    measurementId: 'G-LGD6THZN3V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJsZJrCsNMm0b6UWGYuXrfwW6KEzSFdWE',
    appId: '1:759452227025:android:15a20a400dd5b84dfebcf0',
    messagingSenderId: '759452227025',
    projectId: 'likealocal-c33e9',
    storageBucket: 'likealocal-c33e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-LjdrWc9JX96eRyFDC0ja3C1q4Kk9a1M',
    appId: '1:759452227025:ios:78c98ff7ae563ceffebcf0',
    messagingSenderId: '759452227025',
    projectId: 'likealocal-c33e9',
    storageBucket: 'likealocal-c33e9.firebasestorage.app',
    iosBundleId: 'com.example.likeALocal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-LjdrWc9JX96eRyFDC0ja3C1q4Kk9a1M',
    appId: '1:759452227025:ios:78c98ff7ae563ceffebcf0',
    messagingSenderId: '759452227025',
    projectId: 'likealocal-c33e9',
    storageBucket: 'likealocal-c33e9.firebasestorage.app',
    iosBundleId: 'com.example.likeALocal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDR6c3Ad0brmryK_fpekSrmPHUK4ByeByM',
    appId: '1:759452227025:web:ebf8b8f2eed5a580febcf0',
    messagingSenderId: '759452227025',
    projectId: 'likealocal-c33e9',
    authDomain: 'likealocal-c33e9.firebaseapp.com',
    storageBucket: 'likealocal-c33e9.firebasestorage.app',
    measurementId: 'G-9ZMLPH5S28',
  );
}
